name: Main Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BuildConfiguration: Release
  DataJsonPackageId: ServantSoftware.Data.Json
  DataJsonPackageVersion: 1.0.0.${{github.run_number}}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Set version number
      run:  '& ${{github.workspace}}/.github/workflows/UpdateVersion.ps1 ${{github.run_number}}'
      shell: pwsh

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration $BuildConfiguration

    - name: Test
      run: dotnet test DataProviders.sln --configuration $BuildConfiguration --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Create nuget packages
      run: dotnet pack DataProviders.sln --configuration $BuildConfiguration

    - uses: actions/upload-artifact@v3
      with:
        name: Nuget Packages
        path: ${{github.workspace}}/src/**/*.nupkg

#    - name: Push to nuget.org
#      run: dotnet nuget push ${{github.workspace}}/src/Data.Json/bin/$BuildConfiguration/$DataJsonPackageId.$DataJsonPackageVersion.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_ORG_API_KEY }} --skip-duplicate

#    - name: Unlist package at nuget.org
#      run: dotnet nuget delete $DataJsonPackageId $DataJsonPackageVersion -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_ORG_API_KEY }} --non-interactive


    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '40 60'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
