name: Main Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BuildConfiguration: Release
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Set version number
      run:  '& ${{github.workspace}}/.github/workflows/UpdateVersion.ps1 ${{github.run_number}}'
      shell: pwsh

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration $BuildConfiguration

    - name: Create nuget packages
      run: dotnet pack DataProviders.sln --configuration $BuildConfiguration

    - uses: actions/upload-artifact@v3
      with:
        name: Nuget Packages
        path: ${{github.workspace}}/src/**/*.nupkg

